### ISSUE TITLE
GCR images are broken

### ISSUE THREAD

**Issue by davidkarlsen** [paketo-buildpacks/builder-jammy-tiny#184] opened 2023-04-25 15:41 UTC
## Expected Behavior
GCR images should work like docker.io ones

## Current Behavior
gcr.io/paketo-buildpacks/build-jammy-tiny fails with:
```shell
Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.0.6:build-image (default-cli) on project ei-bgc: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:3.0.6:build-image failed: No 'io.buildpacks.builder.metadata' label found in image config labels 'io.buildpacks.stack.description,io.buildpacks.stack.distro.name,io.buildpacks.stack.distro.version,io.buildpacks.stack.homepage,io.buildpacks.stack.id,io.buildpacks.stack.maintainer,io.buildpacks.stack.metadata,io.buildpacks.stack.released,org.opencontainers.image.ref.name,org.opencontainers.image.version' -> [Help 1]
```

while
              <builder>paketobuildpacks/builder-jammy-tiny</builder>
works fine

## Possible Solution
Have same metadata on all iamges

## Steps to Reproduce
1. do a spring-boot build of images which uses packeto under the covers

## Motivations
Avoid docker hub which have ever changing policies and limits.

**Comment by robdimsdale** [comment] 2023-05-10 03:00
@davidkarlsen I think there's some confusion here - `paketobuildpacks/builder-jammy-tiny` is a _builder_ but `gcr.io/paketo-buildpacks/build-jammy-tiny` is a _stack build image_.

The problem isn't that the metadata is missing, it's that you're trying to use a stack build image in place of a builder.

That being said, the underlying request is valid. I don't believe we publish builders to gcr.io. I'm not necessarily averse to it, but it's not something that's currently top of our priority list.

**Comment by davidkarlsen** [comment] 2023-05-29 22:30
> @davidkarlsen I think there's some confusion here - `paketobuildpacks/builder-jammy-tiny` is a _builder_ but `gcr.io/paketo-buildpacks/build-jammy-tiny` is a _stack build image_.
> 
> The problem isn't that the metadata is missing, it's that you're trying to use a stack build image in place of a builder.
> 
> That being said, the underlying request is valid. I don't believe we publish builders to gcr.io. I'm not necessarily averse to it, but it's not something that's currently top of our priority list.

Aha, I was confused by the similar naming.

**Comment by robdimsdale** [comment] 2023-06-22 23:17
I'm going to close this issue as the actual problem seems to be resolved. We'll track the gcr.io request separately.

**Closed by robdimsdale** 2023-06-22 23:17 UTC
